version: '3.7'
services:
  bookstore:
    container_name: ednevnik
    build: .
    image: ednevnik:latest
    ports:
      - 80:80
    networks:
      - ednevnik-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - ednevnik-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=role
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
networks:
  ednevnik-network:
    driver: bridge